### ISSUE TITLE
How to generate the 'update.zip' for OTA?

### ISSUE THREAD

**Issue by ender503** [rbx-rdm/documentation#7]
I just follow the instruction[[link]](https://github.com/rbx-rdm/documentation) to build the android firmware(android-eng), and it run without any problem. 👍 

After I build the android firmware, I cannot find the update.zip file in the /out. 

Did I miss some step to generate the `update.zip` file?

By the way, I found these message in the `Build Uboot` step.
What does purpose of these files? 🤔 
```
cat: .RIDI_VERSION: No such file or directory
cat: .RIDI_MODELCODE: No such file or directory
cat: .RIDI_EXTRACODE: No such file or directory
cat: .RIDI_DATECODE: No such file or directory
```

**Comment by YSYoon** [comment]
Hello @ender503 

## Using setup.sh

Those files (`.RIDI_*`) are created by **setup.sh** script.
Ridi's current file name format is as follows:
`update-1.0.2P-RC2-2018020701.zip`
update : default prefix
1.0.2 : version number (**.RIDI_VERSION**)
P : model code (**.RIDI_MODELCODE**)
RC2 : extra info to indicate which custom version this is - in this case Release Candidate 2 (**.RIDI_EXTRACODE**)
2018020701 : date YYYYMMDD and build number of that date (**.RIDI_DATECODE**)

You can customize or remove these parameters by going through **setup.sh** and **build_android-img.sh**, but be sure to find and change all the scripts where these values and files are used.

## Creating update.zip file

Script required for creating update.zip file is inside ntx_addon/host_tools/

```
cd ntx_addon/host_tools
./mk_update_zip_package.sh all
```

This will create **update.zip** inside `out` directory, and then make a copy in `rom` directory using information from **setup.sh** script

There are other options besides `all`, but I don't think you'll need other options right now, so I'll include extra information when I update documentation.

Thank you

**Comment by ender503** [comment]
Hi @YSYoon

Sorry for the delayed response, I check the device that Ridibooks sent to me.

```
$ adb -d shell getprop | grep ro.build
[ro.build.characteristics]: [tablet]
[ro.build.date.utc]: [1519097138]
[ro.build.date]: [Tue Feb 20 12:25:38 KST 2018]
[ro.build.description]: [ntx_6sl-userdebug 4.4.2 KOT49H eng.ridi.20180220.122458 release-keys]
[ro.build.display.id]: [KOT49H.eng.ridi.20180220.122458]
[ro.build.fingerprint]: [Freescale/ntx_6sl/ntx_6sl:4.4.2/KOT49H/eng.ridi.20180220.122458:userdebug/release-keys]
[ro.build.host]: [ridi-All-Series]
[ro.build.id]: [KOT49H]
[ro.build.product]: [PAPER_PRO]
[ro.build.tags]: [release-keys]
[ro.build.type]: [userdebug]
[ro.build.user]: [ridi]
[ro.build.version.codename]: [REL]
[ro.build.version.incremental]: [eng.ridi.20180220.122458]
[ro.build.version.release]: [4.4.2]
[ro.build.version.sdk]: [19] 
```
It seems like the device is using `userdebug` Android firmware.


## Build Android firmware (userdebug)

So I clone the pp1 repoistory again, and follow the instruction to build the Android firmware with `$ ./build_android_img.sh android-userdebug`.

I find these message at the end of execution.

```
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
cp: cannot stat `boot.img': No such file or directory
cp: cannot stat `recovery.img': No such file or directory
cp: cannot stat `system.img': No such file or directory
spawn ./build/tools/releasetools/sign_target_files_apks -e Msg_E6.apk,com.wordwebsoftware.android.wordweb.apk,com.halbae87.koreanbasicime.apk,com.ridi.paper.apk=vendor/ntx/security/ntx_6sl/platform -o -d vendor/ntx/security/ntx_6sl out/dist/ntx_6sl-target_files-eng.readmoo.zip out/dist/ntx_6sl-signed_target_files-eng.readmoo.zip
Traceback (most recent call last):
  File "./build/tools/releasetools/sign_target_files_apks", line 390, in <module>
    main(sys.argv[1:])
  File "./build/tools/releasetools/sign_target_files_apks", line 366, in main
    input_zip = zipfile.ZipFile(args[0], "r")
  File "/usr/lib/python2.7/zipfile.py", line 701, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: 'out/dist/ntx_6sl-target_files-eng.readmoo.zip'
unzip:  cannot find or open out/dist/ntx_6sl-signed_target_files-eng.readmoo.zip, out/dist/ntx_6sl-signed_target_files-eng.readmoo.zip.zip or out/dist/ntx_6sl-signed_target_files-eng.readmoo.zip.ZIP.

   ERROR: failed to unzip input target-files "out/dist/ntx_6sl-signed_target_files-eng.readmoo.zip"

unzip:  cannot find or open out/dist/signed-images.zip, out/dist/signed-images.zip.zip or out/dist/signed-images.zip.ZIP.
cp: cannot stat `out/dist/recovery.img': No such file or directory
unzip:  cannot find or open out/dist/ntx_6sl-signed_target_files-eng.readmoo.zip, out/dist/ntx_6sl-signed_target_files-eng.readmoo.zip.zip or out/dist/ntx_6sl-signed_target_files-eng.readmoo.zip.ZIP.
mv: cannot stat `out/dist/RECOVERY': No such file or directory
cp: cannot stat `out/dist/recovery/RAMDISK': No such file or directory
unzip:  cannot find or open out/dist/signed-images.zip, out/dist/signed-images.zip.zip or out/dist/signed-images.zip.ZIP.
cp: cannot stat `out/dist/system.img': No such file or directory
unzip:  cannot find or open out/dist/ntx_6sl-signed_target_files-eng.readmoo.zip, out/dist/ntx_6sl-signed_target_files-eng.readmoo.zip.zip or out/dist/ntx_6sl-signed_target_files-eng.readmoo.zip.ZIP.
unzip:  cannot find or open out/dist/ntx_6sl-signed_target_files-eng.readmoo.zip, out/dist/ntx_6sl-signed_target_files-eng.readmoo.zip.zip or out/dist/ntx_6sl-signed_target_files-eng.readmoo.zip.ZIP.
mv: cannot stat `out/dist/SYSTEM': No such file or directory
cp: cannot stat `out/dist/system': No such file or directory
cp: cannot stat `out/dist/META': No such file or directory
It took 1895 seconds

```

It seems weird, and I find a document in `/ntx_addon/ntx_docs/E60Q_Series_Android_4.4.2_Development_Quick_Guide.pdf`

> Once the build process is successful, you can find system.img, ramdisk.img, recovery.img in directory ./out/target/product/ntx_6sl

Here is my `/out/target/product/ntx_6sl` directory.

```
$ ls /out/target/product/ntx_6sl
android-info.txt clean_steps.mk fake_packages kernel obj previous_build_config.mk recovery root symbols u-boot.bin u-boot_E70Q12.bin uImage

```



## Creating update.zip file

If I ignore the message above, continue to creating update.zip file.
```
$ ./mk_update_zip_package.sh all
/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/jdk1.6.0_45/bin/:.
------- release key mode -------
Sorry, the file "/home/readmoo/.sign_pass" was not found !
Please enter password for platform.key: android
-------remove exist file-------
-------copy upgrade files-------
cp: cannot stat /home/readmoo/pp1/ntx_addon/host_tools/../../out/target/product/ntx_6sl/boot.img': No such file or directory cp: cannot stat/home/readmoo/pp1/ntx_addon/host_tools/../../out/target/product/ntx_6sl/system': No such file or directory
cp: cannot stat /home/readmoo/pp1/ntx_addon/host_tools/../../out/target/product/ntx_6sl/META': No such file or directory cp: cannot stat/home/readmoo/pp1/ntx_addon/host_tools/../../out/target/product/ntx_6sl/recovery.img': No such file or directory
cp: cannot stat /home/readmoo/pp1/ntx_addon/host_tools/../../out/target/product/ntx_6sl/symbols/system/bin/updater': No such file or directory rm: cannot remove/home/readmoo/pp1/ntx_addon/host_tools/../../out/tmp/ntx_6sl/tmp_update/META-INF/com/google/android/upgrade.sh_*': No such file or directory
---> copy mdpi logo raw4 file ----------------------------------------
jpegtopnm: WRITING PGM FILE
NtxHwCfg_GetCfgFldStrVal:[WARNING]Config version too old !! Please update config file !!
[10] DisplayPanel='6" Bottom EPD'
angle is "270"
file name is "/home/readmoo/pp1/ntx_addon/host_tools/../../ntx_addon/images/mdpi_logo.jpg.raw4"

Read Bytes:480000

Rotate=3,Write Bytes:240000
---> copy mdpi logo header file ----------------------------------------
header = /home/readmoo/pp1/ntx_addon/host_tools/../../ntx_addon/images/mdpi_logo.jpg.header
16+0 records in
16+0 records out
16 bytes (16 B) copied, 5.3646e-05 s, 298 kB/s
write bin signature...
write bin info swap pattern...
write bin size 240000...
---> copy hdpi logo raw4 file ----------------------------------------
jpegtopnm: WRITING PPM FILE
NtxHwCfg_GetCfgFldStrVal:[WARNING]Config version too old !! Please update config file !!
[10] DisplayPanel='7.8" Bottom EPD'
angle is "270"
file name is "/home/readmoo/pp1/ntx_addon/host_tools/../../ntx_addon/images/hdpi_logo.jpg.raw4"

Read Bytes:776192

Rotate=3,Write Bytes:388096
---> copy hdpi logo header file ----------------------------------------
header = /home/readmoo/pp1/ntx_addon/host_tools/../../ntx_addon/images/hdpi_logo.jpg.header
16+0 records in
16+0 records out
16 bytes (16 B) copied, 6.2665e-05 s, 255 kB/s
write bin signature...
write bin info swap pattern...
write bin size 388096...
---> copy xhdpi logo raw4 file ----------------------------------------
jpegtopnm: WRITING PPM FILE
NtxHwCfg_GetCfgFldStrVal:[WARNING]Config version too old !! Please update config file !!
[10] DisplayPanel='6" Bottom EPD'
angle is "270"
file name is "/home/readmoo/pp1/ntx_addon/host_tools/../../ntx_addon/images/xhdpi_logo.jpg.raw4"

Read Bytes:1552256

Rotate=3,Write Bytes:776128
---> copy xhdpi logo header file ----------------------------------------
header = /home/readmoo/pp1/ntx_addon/host_tools/../../ntx_addon/images/xhdpi_logo.jpg.header
16+0 records in
16+0 records out
16 bytes (16 B) copied, 6.3564e-05 s, 252 kB/s
write bin signature...
write bin info swap pattern...
write bin size 776128...
-------creat update.zip-------
-------sign update.zip-------
spawn java -jar /home/readmoo/pp1/ntx_addon/host_tools/../../out/host/linux-x86/framework/signapk.jar -w /home/readmoo/pp1/ntx_addon/host_tools/../../vendor/ntx/security/ntx_6sl/releasekey.x509.pem /home/readmoo/pp1/ntx_addon/host_tools/../../vendor/ntx/security/ntx_6sl/releasekey.pk8 update_unsigned.zip update.zip
Unable to access jarfile /home/readmoo/pp1/ntx_addon/host_tools/../../out/host/linux-x86/framework/signapk.jar
------- The update.zip has been generated in /home/readmoo/pp1/ntx_addon/host_tools/../../out/tmp/ntx_6sl/update.zip -------
-------create version.ntx-------
cat: /home/readmoo/pp1/ntx_addon/host_tools/../../out/target/product/ntx_6sl/system/build.prop: No such file or directory
-------create md5.sum-------
md5sum: update.zip: No such file or directory

ls: cannot access update.zip: No such file or directory

<---[MD5 sum] =
cp: cannot stat `update.zip': No such file or directory
```

The `update.zip` file is not generated in the `rom` folder. 

```
$ ls rom/
bin etc fastboot_pcc.sh image image_adb image_adb.tar.gz image.tar.gz setup.sh tmp update_image.sh update_waveform.sh waveform_img waveform_img.tar.gz write_sn.sh write_vcom.sh
```

Did I miss some steps? 🤔 

Thanks!

**Comment by YSYoon** [comment]
@ender503 

We use userdebug build only for enabling ADB on customers' devices (we previously suggested using userdebug image because your computer was not set up to build firmware at that time). Now that you have your build machine set up, I'd recommend using eng build (`android-eng`) for development and testing purposes.

As for the error in `build firmware` section, I think there was some other error before the script reached that point. 
```
cp: cannot stat `boot.img': No such file or directory
cp: cannot stat `recovery.img': No such file or directory
cp: cannot stat `system.img': No such file or directory
```
These lines seem to indicate that something went wrong, but I can't really tell what exactly went wrong from your logs. If you're building on `master` branch, could you try again on `develop` branch and see if same error occurs?

If building firmware was not successfully completed, you probably won't have files required for creating update.zip file.

**Comment by ender503** [comment]
@YSYoon 
> These lines seem to indicate that something went wrong, but I can't really tell what exactly went wrong from your logs. If you're building on master branch, could you try again on develop branch and see if same error occurs?

The above error comes up when I was using `develop` branch to build Android firmware.

I find out my jdk1.6.0_45 environment is not set properly, I was not set the environment variable `JAVA_HOME` and `ANDROID_JAVA_HOME` 

Here is my current ~/.bashrc setting
```
export JAVA_HOME=/opt/jdk_1.6.0
export ANDROID_JAVA_HOME=$JAVA_HOME
export PATH=$JAVA_HOME/bin/:$PATH
```

After setting these environment variables, the android firmware can be built nicely, and I can generate the `update-1.0.2PP-2018042501.zip` in `/rom` directory.

Cheers! 🎉 🎉 🎉 🎉
